### ISSUE TITLE
Error thrown when trying to run the latest saltlib release

### ISSUE THREAD

**Issue by u9g** [DeexCoding/SaltLib#2]
Error thrown: 
```
java.lang.NoSuchMethodError: 'java.util.List net.minecraft.client.render.VertexFormat.method_10344()'
	at net.minecraft.client.render.BufferBuilder.nextElement(BufferBuilder.java:591)
	at net.minecraft.client.render.BufferBuilder.vertex(BufferBuilder.java:414)
	at net.minecraft.client.MinecraftClient.loadLogo(MinecraftClient.java:729)
	at net.minecraft.client.MinecraftClient.initializeGame(MinecraftClient.java:397)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:331)
	at net.minecraft.client.main.Main.main(Main.java:111)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by DeexCoding** [comment]
I developed that version with an older version of Legacy Fabric, I'll try and release an update, but no guarantees, sorry

**Comment by DeexCoding** [comment]
Updated the fabric mappings and released a patch, it should run fine now!
